import api from './api';

export const similarityService = {
  /**
   * Fetches the candidate semantic matches currently generated by the similarity index.
   */
  getMatches: async () => {
    const response = await api.get('/similarity/matches');
    return response.data;
  }
};

export default similarityService;
